on: [push]
jobs:
  docker-build:
    name: Create ivar 1.3 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Prepare
        id: prep
        run: |
          BASE_PATH=ghcr.io/${{ github.actor }}/covid-seq
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${BASE_PATH}/${VERSION}/ivar:1.3_nsc"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container-images/Docker/ivar_1_3_Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
  docker-build:
    name: Create nsc_r image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Prepare
        id: prep
        run: |
          BASE_PATH=ghcr.io/${{ github.actor }}/covid-seq
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${BASE_PATH}/${VERSION}/nsc_r:1.0"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container-images/Docker/nsc_r_Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}